version: "3"

volumes:
  cloudbeaver: {}
  cloudbeaver_certs: {}
  postgres_data: {}
  nginx_ssl_data: {}
  nginx_conf_data: {}
  trusted_cacerts: {}

networks:
  cloudbeaver-private-net:

services:
  nginx:
    restart: unless-stopped
    image: $IMAGE_SOURCE/dbeaver-nginx:${CLOUDBEAVER_VERSION_TAG}
    ports:
      - 80:8080
      - 443:8443
    env_file:
      - .env  
    networks:
      - cloudbeaver-private-net
    volumes:
      - nginx_conf_data:/etc/nginx/product-conf/
      - nginx_ssl_data:/etc/nginx/ssl/
    depends_on:
      - cloudbeaver

  cloudbeaver:
    restart: unless-stopped
    hostname: cloudbeaver
    image: $IMAGE_SOURCE/cloudbeaver-ee:${CLOUDBEAVER_VERSION_TAG}
    deploy:
      replicas: ${REPLICA_COUNT_EE:-1}
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
      - cloudbeaver_certs:/opt/cloudbeaver/conf/certificates/
      - trusted_cacerts:/opt/cloudbeaver/workspace/.data/custom/
    environment:
      - CLOUDBEAVER_DB_DRIVER=${CLOUDBEAVER_DB_DRIVER}
      - CLOUDBEAVER_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_DB_SCHEMA=${CLOUDBEAVER_DB_SCHEMA}
      - CLOUDBEAVER_QM_DB_DRIVER=${CLOUDBEAVER_QM_DB_DRIVER}
      - CLOUDBEAVER_QM_DB_URL=${CLOUDBEAVER_QM_DB_URL}
      - CLOUDBEAVER_QM_DB_USER=${CLOUDBEAVER_QM_DB_USER}
      - CLOUDBEAVER_QM_DB_PASSWORD=${CLOUDBEAVER_QM_DB_PASSWORD}
      - CLOUDBEAVER_QM_DB_SCHEMA=${CLOUDBEAVER_QM_DB_SCHEMA}
    expose:
      - ${CLOUDBEAVER_WEB_SERVER_PORT:-8978}
    depends_on:
      - postgres
    networks:
      - cloudbeaver-private-net

  postgres:
    restart: unless-stopped
    hostname: postgres
    image: ${IMAGE_SOURCE:-dbeaver}/dbeaver-postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=${CLOUDBEAVER_DB_USER}
      - POSTGRES_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
    expose:
      - 5432
    networks:
      - cloudbeaver-private-net


