version: "3"

volumes:
  cloudbeaver: {}
  nginx_ssl_data: {}
  nginx_conf_data: {}

networks:
  cloudbeaver-private-net:

services:
  nginx:
    restart: unless-stopped
    image: $IMAGE_SOURCE/cloudbeaver-nginx:${CLOUDBEAVER_VERSION_TAG}
    ports:
      - 80:80
      - 443:443
    networks:
      - cloudbeaver-private-net
    volumes:
      - nginx_conf_data:/etc/nginx/product-conf/
      - nginx_ssl_data:/etc/letsencrypt/
    depends_on:
      - cloudbeaver

  cloudbeaver:
    restart: unless-stopped
    hostname: cloudbeaver
    image: $IMAGE_SOURCE/cloudbeaver-ee:${CLOUDBEAVER_VERSION_TAG}
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    expose:
      - 8978
    networks:
      - cloudbeaver-private-net
