version: "3"

volumes:
  cloudbeaver: {}
  cloudbeaver_certs: {}
  postgres_data: {}
  nginx_ssl_data: {}
  nginx_conf_data: {}

services:
  web-proxy:
    restart: unless-stopped
    image: ${IMAGE_SOURCE}/cloudbeaver-${PROXY_TYPE:-haproxy}:${CLOUDBEAVER_VERSION_TAG}
    network_mode: host
    environment:
      - NETWORK_MODE=host
      - LISTEN_PORT_HTTP=80
      - LISTEN_PORT_HTTPS=443
    volumes:
      - nginx_conf_data:/etc/${PROXY_TYPE:-haproxy}/product-conf/
      - nginx_ssl_data:/etc/${PROXY_TYPE:-haproxy}/ssl/
    depends_on:
      - cloudbeaver

  cloudbeaver:
    image: $IMAGE_SOURCE/cloudbeaver-ee:${CLOUDBEAVER_VERSION_TAG}
    hostname: cloudbeaver
    network_mode: host
    restart: unless-stopped
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
      - cloudbeaver_certs:/opt/cloudbeaver/conf/certificates/
    environment:
      - CLOUDBEAVER_DB_DRIVER=${CLOUDBEAVER_DB_DRIVER}
      - CLOUDBEAVER_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_DB_SCHEMA=${CLOUDBEAVER_DB_SCHEMA}
      - CLOUDBEAVER_QM_DB_DRIVER=${CLOUDBEAVER_QM_DB_DRIVER}
      - CLOUDBEAVER_QM_DB_URL=${CLOUDBEAVER_QM_DB_URL}
      - CLOUDBEAVER_QM_DB_USER=${CLOUDBEAVER_QM_DB_USER}
      - CLOUDBEAVER_QM_DB_PASSWORD=${CLOUDBEAVER_QM_DB_PASSWORD}
      - CLOUDBEAVER_QM_DB_SCHEMA=${CLOUDBEAVER_QM_DB_SCHEMA}
      - CLOUDBEAVER_DMSVC_URL=http://127.0.0.1:11000
    depends_on:
      - postgres

  postgres:
    restart: unless-stopped
    hostname: postgres
    network_mode: host
    image: ${IMAGE_SOURCE:-dbeaver}/cloudbeaver-postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./cloudbeaver-db-init.sql:/docker-entrypoint-initdb.d/cb-init.sql
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=${CLOUDBEAVER_DB_USER}
      - POSTGRES_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
