# run as root before up this compose:
#   loginctl enable-linger 1000
#   echo 'net.ipv4.ip_unprivileged_port_start=80' >> /etc/sysctl.conf
#   sysctl -p

version: '3'
volumes:
  cloudbeaver: {}
  cloudbeaver_certs: {}
  postgres_data: {}
  nginx_ssl_data: {}
  nginx_conf_data: {}
  trusted_cacerts:  {}
  api_tokens: {}
networks:
  cloudbeaver-private-net: null
services:
  web-proxy:
    restart: unless-stopped
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-${PROXY_TYPE:-haproxy}:${CLOUDBEAVER_VERSION_TAG}
    ports:
      - 80:8080
      - 443:8443
    environment:
      - CLOUDBEAVER_WEB_SERVER_PORT=${CLOUDBEAVER_WEB_SERVER_PORT:-8978}
    networks:
      - cloudbeaver-private-net
    volumes:
      - nginx_conf_data:/etc/${PROXY_TYPE:-haproxy}/product-conf/:z
      - nginx_ssl_data:/etc/${PROXY_TYPE:-haproxy}/ssl/:z
    depends_on:
      - cloudbeaver
  cloudbeaver:
    restart: unless-stopped
    hostname: cloudbeaver
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-ee:${CLOUDBEAVER_VERSION_TAG}
    deploy:
      replicas: ${REPLICA_COUNT_EE:-1}
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace:z
      - cloudbeaver_certs:/opt/cloudbeaver/conf/certificates/:z
      - trusted_cacerts:/opt/cloudbeaver/workspace/.data/custom/:z
      - api_tokens:/opt/cloudbeaver/conf/keys/:z
    environment:
      - CLOUDBEAVER_DB_DRIVER=${CLOUDBEAVER_DB_DRIVER}
      - CLOUDBEAVER_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_DB_SCHEMA=${CLOUDBEAVER_DB_SCHEMA}
      - CLOUDBEAVER_QM_DB_DRIVER=${CLOUDBEAVER_QM_DB_DRIVER}
      - CLOUDBEAVER_QM_DB_URL=${CLOUDBEAVER_QM_DB_URL}
      - CLOUDBEAVER_QM_DB_USER=${CLOUDBEAVER_QM_DB_USER}
      - CLOUDBEAVER_QM_DB_PASSWORD=${CLOUDBEAVER_QM_DB_PASSWORD}
      - CLOUDBEAVER_QM_DB_SCHEMA=${CLOUDBEAVER_QM_DB_SCHEMA}
    expose:
      - ${CLOUDBEAVER_WEB_SERVER_PORT:-8978}
    depends_on:
      - postgres
    networks:
      - cloudbeaver-private-net
  postgres:
    restart: unless-stopped
    hostname: postgres
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
      - ./cloudbeaver-db-init.sql:/docker-entrypoint-initdb.d/cb-init.sql:z
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=${CLOUDBEAVER_DB_USER}
      - POSTGRES_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
    expose:
      - 5432
    networks:
      - cloudbeaver-private-net
