# run as root before up this compose:
#   loginctl enable-linger 1000
#   echo 'net.ipv4.ip_unprivileged_port_start=80' >> /etc/sysctl.conf
#   sysctl -p

version: '3'
volumes:
  cloudbeaver: {}
  cloudbeaver_certs: {}
  postgres_data: {}
  haproxy_ssl_data: {}
  haproxy_conf_data: {}
networks:
  cloudbeaver-private-net: null
services:
  haproxy:
    restart: unless-stopped
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-proxy:${CLOUDBEAVER_VERSION_TAG}
    ports:
      - 80:8080
      - 443:8443
    environment:
      - CLOUDBEAVER_WEB_SERVER_PORT=${CLOUDBEAVER_WEB_SERVER_PORT:-8978}
    networks:
      - cloudbeaver-private-net
    volumes:
      - haproxy_conf_data:/etc/haproxy/conf/:z
      - haproxy_ssl_data:/etc/haproxy/ssl/:z
    depends_on:
      - cloudbeaver
  cloudbeaver:
    restart: unless-stopped
    hostname: cloudbeaver
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-ee:${CLOUDBEAVER_VERSION_TAG}
    deploy:
      replicas: ${REPLICA_COUNT_EE:-1}
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace:z
      - cloudbeaver_certs:/opt/cloudbeaver/conf/certificates/:z
    environment:
      - CLOUDBEAVER_DB_DRIVER=${CLOUDBEAVER_DB_DRIVER}
      - CLOUDBEAVER_DB_URL=${CLOUDBEAVER_DB_URL}
      - CLOUDBEAVER_DB_USER=${CLOUDBEAVER_DB_USER}
      - CLOUDBEAVER_DB_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
      - CLOUDBEAVER_DB_SCHEMA=${CLOUDBEAVER_DB_SCHEMA}
      - CLOUDBEAVER_QM_DB_DRIVER=${CLOUDBEAVER_QM_DB_DRIVER}
      - CLOUDBEAVER_QM_DB_URL=${CLOUDBEAVER_QM_DB_URL}
      - CLOUDBEAVER_QM_DB_USER=${CLOUDBEAVER_QM_DB_USER}
      - CLOUDBEAVER_QM_DB_PASSWORD=${CLOUDBEAVER_QM_DB_PASSWORD}
      - CLOUDBEAVER_QM_DB_SCHEMA=${CLOUDBEAVER_QM_DB_SCHEMA}
      - CLOUDBEAVER_DMSVC_URL=http://haproxy:11000
    expose:
      - ${CLOUDBEAVER_WEB_SERVER_PORT:-8978}
    depends_on:
      - postgres
    networks:
      - cloudbeaver-private-net
  postgres:
    restart: unless-stopped
    hostname: postgres
    image: ${PODMAN_IMAGE_SOURCE:-docker.io/dbeaver}/cloudbeaver-postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
      - ./cloudbeaver-db-init.sql:/docker-entrypoint-initdb.d/cb-init.sql:z
    environment:
      - POSTGRES_DB=cloudbeaver
      - POSTGRES_USER=${CLOUDBEAVER_DB_USER}
      - POSTGRES_PASSWORD=${CLOUDBEAVER_DB_PASSWORD}
    expose:
      - 5432
    networks:
      - cloudbeaver-private-net
