---
{{- if eq .Values.ingressController "nginx" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  annotations:
    {{- if eq "https" .Values.httpScheme }}
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: "/$1$2"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "cb-node-id"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/session-cookie-domain: "{{ .Values.cloudbeaverBaseDomain }}"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "345600"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"    
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: "nginx"
{{- if eq "https" .Values.httpScheme }}
  tls:
    - hosts:
      - {{ .Values.cloudbeaverBaseDomain }}
      secretName: {{ .Release.Name }}-ingress-tls
{{- end }}
  rules:
  - host: "{{ .Values.cloudbeaverBaseDomain }}"
    http:
      paths:
        - path: /(.*)(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: cloudbeaver
              port:
                number: 8978        
{{ end }}